'use client';
import { Alert, AlertIcon, Badge, Box, Button, Checkbox, Flex, FormControl, FormLabel, Input, Progress, Select, SimpleGrid, Spinner, Text, useColorModeValue } from '@chakra-ui/react';
import Card from 'components/card/Card';
import { useCallback, useEffect, useMemo, useState } from 'react';

const labels: Record<string,string> = { PREPARATION:'Przygotowanie', READY_TO_SUBMIT:'Gotowe do wysłania', SUBMITTED:'Wysłane', CORRECTION_REQUIRED:'Do poprawy', ACCEPTED:'Zaakceptowane', METER_WORK:'Prace licznikowe', COMPLETED:'Zakończone', CANCELLED:'Anulowane' };
async function data(r:Response){const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.message||p.error);return p.data;}
export default function OsdWorkspace(){
 const [cases,setCases]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[projectId,setProjectId]=useState(''),[selectedId,setSelectedId]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const text=useColorModeValue('secondaryGray.900','white'),muted=useColorModeValue('secondaryGray.600','secondaryGray.400'),border=useColorModeValue('secondaryGray.200','whiteAlpha.200');
 const load=useCallback(async()=>{setLoading(true);try{const p=await data(await fetch('/api/osd',{cache:'no-store'}));setCases(p.cases||[]);setProjects(p.projects||[]);setSelectedId((id)=>p.cases.some((x:any)=>x.id===id)?id:p.cases[0]?.id||'');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 const selected=cases.find(x=>x.id===selectedId)||cases[0];const done=selected?.checklistItems.filter((x:any)=>x.completed).length||0,total=selected?.checklistItems.length||0;
 const stats=useMemo(()=>({open:cases.filter(x=>!['COMPLETED','CANCELLED'].includes(x.status)).length,correction:cases.filter(x=>x.status==='CORRECTION_REQUIRED').length,submitted:cases.filter(x=>x.status==='SUBMITTED').length,completed:cases.filter(x=>x.status==='COMPLETED').length}),[cases]);
 async function create(){setSaving(true);setError('');try{const c=await data(await fetch('/api/osd',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId})}));setCases(x=>[c,...x]);setSelectedId(c.id);setNotice('Utworzono sprawę OSD z checklistą dokumentów.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}
 async function patch(body:any){if(!selected)return;setSaving(true);try{const c=await data(await fetch('/api/osd',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,...body})}));setCases(x=>x.map(y=>y.id===c.id?c:y));setNotice('Zapisano sprawę OSD.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}
 if(loading)return <Flex pt="100px" justify="center"><Spinner/></Flex>;
 return <Flex direction="column" pt={{base:'130px',md:'80px'}} gap="20px"><Card p="24px"><Text color={muted} fontWeight="700">Realizacja</Text><Text color={text} fontSize="3xl" fontWeight="900">OSD i odbiory</Text><Text color={muted}>Jedna sprawa formalna na projekt, komplet dokumentów i terminy operatora.</Text></Card>{error?<Alert status="error"><AlertIcon/>{error}</Alert>:null}{notice?<Alert status="success"><AlertIcon/>{notice}</Alert>:null}
 <SimpleGrid columns={{base:2,xl:4}} gap="12px">{[['Otwarte',stats.open],['Do poprawy',stats.correction],['Wysłane',stats.submitted],['Zakończone',stats.completed]].map(([n,v])=><Card key={String(n)} p="16px"><Text color={muted}>{n}</Text><Text color={text} fontSize="2xl" fontWeight="900">{v}</Text></Card>)}</SimpleGrid>
 <Card p="20px"><Flex gap="12px" align="end" wrap="wrap"><FormControl flex="1" minW="280px"><FormLabel>Projekt po montażu</FormLabel><Select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Wybierz projekt</option>{projects.map(p=><option key={p.id} value={p.id}>{p.client.displayName} - {p.title}{p.odsCase?' (ma sprawę)':''}</option>)}</Select></FormControl><Button colorScheme="purple" onClick={create} isDisabled={!projectId} isLoading={saving}>Utwórz sprawę OSD</Button></Flex></Card>
 <SimpleGrid columns={{base:1,'2xl':2}} gap="20px"><Card p="18px"><Text color={text} fontWeight="900" mb="10px">Sprawy</Text><Flex direction="column" gap="8px">{cases.map(c=><Box as="button" key={c.id} textAlign="left" border="1px solid" borderColor={selected?.id===c.id?'purple.300':border} borderRadius="8px" p="11px" onClick={()=>setSelectedId(c.id)}><Flex justify="space-between"><Box><Text color={text} fontWeight="800">{c.project.client.displayName}</Text><Text color={muted} fontSize="sm">{c.operator} · {c.ppeNumber||'brak PPE'}</Text></Box><Badge>{labels[c.status]}</Badge></Flex></Box>)}</Flex></Card>
 <Card p="20px">{selected?<><Flex justify="space-between" gap="10px"><Box><Text color={text} fontWeight="900" fontSize="lg">{selected.project.client.displayName}</Text><Text color={muted}>{selected.project.title}</Text></Box><Select maxW="210px" value={selected.status} onChange={e=>patch({status:e.target.value})} isDisabled={saving}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Flex><SimpleGrid columns={{base:1,md:2}} gap="10px" my="14px"><FormControl><FormLabel>Numer zgłoszenia</FormLabel><Input defaultValue={selected.applicationNumber||''} onBlur={e=>patch({applicationNumber:e.target.value})}/></FormControl><FormControl><FormLabel>Termin OSD</FormLabel><Input type="date" defaultValue={selected.deadlineAt?.slice(0,10)||''} onBlur={e=>patch({deadlineAt:e.target.value})}/></FormControl></SimpleGrid><Progress value={total?done/total*100:0} colorScheme="green"/><Text color={muted} fontSize="sm" mt="4px">Kompletność {done}/{total}</Text><Flex direction="column" gap="8px" mt="14px">{selected.checklistItems.map((item:any)=><Checkbox key={item.id} isChecked={item.completed} onChange={e=>patch({checklistItems:[{id:item.id,completed:e.target.checked}]})}>{item.title}</Checkbox>)}</Flex></>:<Text color={muted}>Wybierz sprawę.</Text>}</Card></SimpleGrid></Flex>;
}
