ALTER TABLE `Project`
  MODIFY `status` ENUM(
    'LEAD',
    'CZEKA_NA_KALKULACJE',
    'W_TRAKCIE_OBSLUGI',
    'OFERTA_PRZYGOTOWANA',
    'OFERTA_ZAAKCEPTOWANA',
    'ZALICZKA_MONTAZ',
    'PROCEDURA_OSD',
    'ODBIOR',
    'ZAKONCZONY',
    'SERWIS',
    'WSTRZYMANY'
  ) NOT NULL DEFAULT 'LEAD';
