ALTER TABLE `Document`
  MODIFY `type` ENUM(
    'FAKTURA_PRAD',
    'ENEA_ZUZYCIE',
    'ENEA_PRODUKCJA',
    'OFERTA',
    'UMOWA',
    'PROTOKOL',
    'ZDJECIE_MONTAZU',
    'DOKUMENT_OSD',
    'RE_DOKUMENT',
    'PROJEKT_INSTALACJI',
    'DECYZJA_POZWOLENIE',
    'FAKTURA_USLUGOWA',
    'DOKUMENT_TECHNICZNY',
    'INNE'
  ) NOT NULL;
