ALTER TABLE `PipelineStage`
  ADD COLUMN `code` VARCHAR(191) NULL,
  ADD COLUMN `status` ENUM(
    'LEAD', 'CZEKA_NA_KALKULACJE', 'W_TRAKCIE_OBSLUGI',
    'OFERTA_PRZYGOTOWANA', 'OFERTA_ZAAKCEPTOWANA', 'ZALICZKA_MONTAZ',
    'PROCEDURA_OSD', 'ODBIOR', 'ZAKONCZONY', 'SERWIS', 'WSTRZYMANY'
  ) NOT NULL DEFAULT 'W_TRAKCIE_OBSLUGI',
  ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `requiresOwner` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `requiresNextAction` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `source` VARCHAR(191) NOT NULL DEFAULT 'LOCAL';

CREATE UNIQUE INDEX `PipelineStage_code_key` ON `PipelineStage`(`code`);

ALTER TABLE `Project`
  ADD COLUMN `nextActionTitle` VARCHAR(191) NULL,
  ADD COLUMN `nextActionAt` DATETIME(3) NULL,
  ADD COLUMN `closedAt` DATETIME(3) NULL;

CREATE INDEX `Project_nextActionAt_idx` ON `Project`(`nextActionAt`);
